### ISSUE TITLE
Representative structure of Metastable state

### ISSUE THREAD

**Issue by MamtaMohan** [lettis/Clustering#4]
Dear Florian,

I would like to know how you generated representative structure of Metastable state. There is no description in  tutorial and I see no where a structure generated during run.

Shall I assume we have to generate it ourself by backtracking from Metastable state formed by microstates which in turned have frame numbers associated with them, getting frame numbers, overlapping them and building a reference structure and then extract the frame from this set of frames (used to build reference structure) which is closet to it. 

I would appreciate your response.

Mamta

**Comment by lettis** [comment]
Dear Mamta,

yes, the representative structures are constructed by simply filtering the original coordinates for a specific state.

If you store your trajectory either as a plain text file (with one frame per row, starting with the first row) or as Gromacs XTC-file, you can use the 'filter'-option of the clustering binary to do that.
Just give it the original trajectory, the state trajectory (i.e. the cluster information, e.g. microstates or macrostates) and select a state you are interested in.
The clustering binary will then generate a reduced 'trajectory' with all structures assigned to the given state.

You then can load these in e.g. VMD and render a representative structure, either by selecting a single structure or by producing an overlay of structures.

I hope that helps.

Cheers,
  Florian

**Comment by MamtaMohan** [comment]
Thank you. 

I appreciate your help.

Mamta
